name: test-build-latex

on: push

env:
    SOURCE_NAME_THESIS: main-thesis
    SOURCE_NAME_REPORT: main-report
    SOURCE_NAME_SEMINAR: main-seminarreport

jobs:
  build-thesis-pdflatex:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: ./.github/actions/latexmk-and-output
      with:
        job_engine: pdf
        job_source: ${{ env.SOURCE_NAME_THESIS }}
        job_artifact_suffix: -pdflatex
  
  build-thesis-xelatex:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: ./.github/actions/latexmk-and-output
      with:
        job_engine: pdfxe
        job_source: ${{ env.SOURCE_NAME_THESIS }}
        job_artifact_suffix: -xelatex
  
  build-report-pdflatex:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: ./.github/actions/latexmk-and-output
      with:
        job_engine: pdf
        job_source: ${{ env.SOURCE_NAME_REPORT }}
        job_artifact_suffix: -pdflatex
  
  build-report-xelatex:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: ./.github/actions/latexmk-and-output
      with:
        job_engine: pdfxe
        job_source: ${{ env.SOURCE_NAME_REPORT }}
        job_artifact_suffix: -xelatex
  
  build-seminar-pdflatex:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: ./.github/actions/latexmk-and-output
      with:
        job_engine: pdf
        job_source: ${{ env.SOURCE_NAME_SEMINAR }}
        job_artifact_suffix: -pdflatex
  
  build-seminar-xelatex:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: ./.github/actions/latexmk-and-output
      with:
        job_engine: pdfxe
        job_source: ${{ env.SOURCE_NAME_SEMINAR }}
        job_artifact_suffix: -xelatex
